services:
  # --- LE CERVEAU ---
  logic:
    image: ghcr.io/topin2001/deeppool/deeppool-logic:latest
    container_name: deeppool-logic
    volumes:
      - /sys:/sys:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    restart: unless-stopped
    depends_on:
      - influxdb

  # --- LA BASE DE DONNÉES ---
  influxdb:
    image: influxdb:1.8
    container_name: deeppool-influxdb
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=deeppool
    restart: always

  # --- L'INTERFACE GRAPHIQUE ---
  grafana:
    image: grafana/grafana-oss:latest
    container_name: deeppool-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - TZ=Europe/Paris
      - GF_SERVER_ENABLE_GZIP=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    restart: always

  # --- MISES À JOUR ---
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: deeppool-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    restart: always
